on: push
name: build
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.12 linters
      uses: shoukoo/golang-pipeline/go1.11/linter@master
